### ISSUE TITLE
Create UT for Forest service layer

### ISSUE THREAD

**Issue by bkompis** [PA165-MushroomHunter/MushroomHunter#82]

**Comment by bohdancvejn** [comment]
I need your help :( 
Who has any idea how to fix it?

Since yesterday I am not able to compile project - I tried to recompile it one package after another, fix the dependencies(set the auto-import +manually added them into project) and as a last change, I completely cloned project again (new fork, new remotes, pull the current version of the master, etc..)

Still, my IDEA cannot work with JMOCKIT... and when I try to compile service layer, I got error:

[ERROR] /C:/Users/bohdan.cvejn/Documents/MushroomHunter/service/src/main/java/cz/muni/fi/pa165/mushrooms/service/MushroomHunterServiceImpl.java:[31,25] cannot find symbol
  symbol:   method findByNickname(java.lang.String)
  location: variable hunterDao of type cz.muni.fi.pa165.mushrooms.dao.MushroomHunterDao

**Comment by bohdancvejn** [comment]
Already done by Peto - We switched it (Forest for Mushroom)

**Comment by bohdancvejn** [comment]
ForestServiceImplTest created #124
